language: node_js
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y build-essential libavahi-compat-libdnssd-dev libgraphicsmagick++1-dev libarchive-dev
node_js:
- '0.12'
- '0.10'
- 'iojs'
matrix:
  allow_failures:
    - node_js: iojs
